# Generated by Django 4.2.7 on 2023-11-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='mycalvalue',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='userinputvalue',
        ),
    ]
